version: '3.9'
services:
  db:
    image: postgres:15.0-alpine
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=Present100%
    - POSTGRES_DB=imibonano_db
    ports:
    - '5432:5432'
  testdb:
    image: postgres:15.0-alpine
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=Present100%
    - POSTGRES_DB=imibonano_db-test
    ports:
    - '5433:5432'