// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc2gp1ecgDq-1rnnP0N0-OyaU4lcMMYJk',
    appId: '1:817353056436:web:80e6087952a6de86f377e1',
    messagingSenderId: '817353056436',
    projectId: 'imibonano-293b3',
    authDomain: 'imibonano-293b3.firebaseapp.com',
    storageBucket: 'imibonano-293b3.appspot.com',
    measurementId: 'G-LVJG0HN64N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp_n88scl69emyWQJhp_IW-K-YmotDe0k',
    appId: '1:817353056436:android:7effccd7b71ae394f377e1',
    messagingSenderId: '817353056436',
    projectId: 'imibonano-293b3',
    storageBucket: 'imibonano-293b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSdLlSJMjXLQJtfMVDrcfgkTkUcYNh_3E',
    appId: '1:817353056436:ios:497c0d4892345245f377e1',
    messagingSenderId: '817353056436',
    projectId: 'imibonano-293b3',
    storageBucket: 'imibonano-293b3.appspot.com',
    iosClientId: '817353056436-r4apc6finun3q131729b2ad7aag7dgo9.apps.googleusercontent.com',
    iosBundleId: 'com.dating.imibonano',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSdLlSJMjXLQJtfMVDrcfgkTkUcYNh_3E',
    appId: '1:817353056436:ios:497c0d4892345245f377e1',
    messagingSenderId: '817353056436',
    projectId: 'imibonano-293b3',
    storageBucket: 'imibonano-293b3.appspot.com',
    iosClientId: '817353056436-r4apc6finun3q131729b2ad7aag7dgo9.apps.googleusercontent.com',
    iosBundleId: 'com.dating.imibonano',
  );
}
